version: "3.8"

services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
    restart: unless-stopped

  sensor_processor:
    build: ./esp32-c6-sensors
    container_name: sensor_processor
    depends_on:
      - mosquitto
    restart: unless-stopped
    volumes:
      - ./esp32-c6-sensors/logs:/app/logs
      